/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.com;

import com.sun.security.ntlm.Client;
import java.awt.Graphics;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author nguyen van cuong
 */
public class BanDoGame extends javax.swing.JPanel {

    /**
     * Creates new form BanDoGame
     */
    public static final int BATDAU = 1;
    public static final int THIETLAP = 2;
    public static final int NHANTHUA = 3;
    /*
     * Khởi tạo file ảnh
     */
    protected ImageIcon tau1[];
    protected ImageIcon tau2[];
    protected ImageIcon tau3[];
    protected ImageIcon tau4[];
    protected ImageIcon tau5[];
    protected ImageIcon no1[];
    protected ImageIcon no2[];
    protected ImageIcon no3[];
    protected ImageIcon no4[];
    protected ImageIcon no5[];
    protected ImageIcon anhnen;
    /*
     * Khởi tạo vị trí tàu và hướng tàu
     */
    protected Point begin[];
    private int arrImage[];//Giá trị 0 là đứng,1 là nằm ngang
    /*
     * Sử dụng để căn lề tàu trên bản đồ
     */
    private Point XY1[];
    private Point XY2[];
    private Point XY3[];
    private Point XY4[];
    private Point XY5[];
    /*
     * Chiều dài mỗi tàu
     */
    private int length[];
    private boolean isClient;//Kien tra xem chuong trinh o mo hinh nao;
    private int status;//Kiem tra xem chuong trinh o trang thai nao;
    private int serial;
    private int[] local;//Can le toa do di chuyen

    public BanDoGame() {
        initComponents();
        tau1 = new ImageIcon[2];
        tau2 = new ImageIcon[2];
        tau3 = new ImageIcon[2];
        tau4 = new ImageIcon[2];
        tau5 = new ImageIcon[2];
        no1 = new ImageIcon[2];
        no2 = new ImageIcon[2];
        no3 = new ImageIcon[2];
        no4 = new ImageIcon[2];
        no5 = new ImageIcon[2];
        XY1 = new Point[2];
        XY2 = new Point[2];
        XY3 = new Point[2];
        XY4 = new Point[2];
        XY5 = new Point[2];
        begin = new Point[5];
        arrImage = new int[5];
        length = new int[5];
        local = new int[5];
        XY1[0] = new Point(-4, 4);
        XY1[1] = new Point(4, -4);
        XY2[0] = new Point(0, -5);
        XY2[1] = new Point(-5, 0);
        XY3[0] = new Point(-3, -2);
        XY3[1] = new Point(-2, -3);
        XY4[0] = new Point(-2, 0);
        XY4[1] = new Point(0, -2);
        XY5[0] = new Point(0, -3);
        XY5[1] = new Point(-3, 0);
        length[0] = 5;
        length[1] = 2;
        length[2] = 3;
        length[3] = 3;
        length[4] = 4;
        local[0] = 125;
        local[0] = 50;
        local[0] = 125;
        local[0] = 125;
        local[0] = 125;
        tau1[0] = new ImageIcon(this.getClass().getResource("image/TauSanBay2.png"));
        tau1[1] = new ImageIcon(this.getClass().getResource("image/TauSanBay3.png"));
        tau2[0] = new ImageIcon(this.getClass().getResource("image/tauChien2.png"));
        tau2[1] = new ImageIcon(this.getClass().getResource("image/tauChien3.png"));
        tau3[0] = new ImageIcon(this.getClass().getResource("image/tauNgam2.png"));
        tau3[1] = new ImageIcon(this.getClass().getResource("image/tauNgam3.png"));
        tau4[0] = new ImageIcon(this.getClass().getResource("image/tauNgu2.png"));
        tau4[1] = new ImageIcon(this.getClass().getResource("image/tauNgu3.png"));
        tau5[0] = new ImageIcon(this.getClass().getResource("image/tauThuyChien1.png"));
        tau5[1] = new ImageIcon(this.getClass().getResource("image/tauThuyChien2.png"));
//        no1[0] = new ImageIcon(this.getClass().getResource("image/TauSanBay2-no.png"));
//        no1[1] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
//        no2[0] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
//        no2[1] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
//        no3[0] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
//        no3[1] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
//        no4[0] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
//        no4[1] = new ImageIcon(this.getClass().getResource("image/tau1.png"));
        anhnen = new ImageIcon(this.getClass().getResource("image/song cuon.png"));
        status = THIETLAP;
        isClient = false;
        serial = -1;
        this.setDefaultPoint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultPoint() {
        begin[0] = new Point(10, 10);
        begin[1] = new Point(185, 60);
        begin[2] = new Point(110, 85);
        begin[3] = new Point(160, 160);
        begin[4] = new Point(85, 210);
        arrImage[0] = 0;
        arrImage[1] = 1;
        arrImage[2] = 0;
        arrImage[3] = 1;
        arrImage[4] = 1;
        repaint();
    }

    public boolean getNumber(Point point, int number) {
        if (arrImage[number] == 0) {
            if ((((point.x - 10) / 25) == ((begin[number].x - 10) / 25))
                    && (((point.y - 10) / 25) >= ((begin[number].y - 10) / 25))
                    && (((point.y - 10) / 25) < ((begin[number].y - 10) / 25) + length[number])) {
                return true;
            } else {
                return false;
            }
        } else {
            if ((((point.y - 10) / 25) == ((begin[number].y - 10) / 25))
                    && (((point.x - 10) / 25) >= ((begin[number].x - 10) / 25))
                    && (((point.x - 10) / 25) < ((begin[number].x - 10) / 25) + length[number])) {
                return true;
            } else {
                return false;
            }
        }
    }

    public void getLocal(int number) {
    }
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && serial != -1) {
            arrImage[serial] = Math.abs(1 - arrImage[serial]);
        }
        repaint();
//        Point point = new Point(evt.getX(), evt.getY());
//        for (int i = 0; i < 5; i++) {
//            if (getNumber(point, i)) {
//                System.out.println(" Tàu : " + (i + 1));
//            }
//        }
//        if (SwingUtilities.isLeftMouseButton(evt) && evt.getClickCount() == 2) {
//            if (evt.getX() > 10 && evt.getX() < 260 && evt.getY() > 10 && evt.getX() < 260) {
//                Point point = new Point();
//                point.x = (evt.getY() - 10) / 25;
//                point.y = (evt.getX() - 10) / 25;
//            } else if (evt.getX() > 300 && evt.getX() < 550 && evt.getY() > 10 && evt.getY() < 260) {
//                Point point = new Point();
//                point.x = (evt.getY() - 10) / 25;
//                point.y = (evt.getX() - 300) / 25;
//            }
//        }
//        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        if (status == THIETLAP && serial == -1) {
            return;
        }
        if (!isClient) {
            if (evt.getX() > 10 && evt.getX() < 260 && evt.getY() > 10 && evt.getY() < 260) {
                int x, y;
                if (arrImage[serial] == 0) {
                    if (evt.getY() >= 260 - local[serial]) {
                        y = 260 - local[serial];
                    } else {
                        y = evt.getY();
                    }
                    x = evt.getX();
                } else {
                    if (evt.getX() >= 260 - local[serial]) {
                        x = 260 - local[serial];
                    } else {
                        x = evt.getX();
                    }
                    y = evt.getY();
                }
                begin[serial].x = ((x - 10) / 25) * 25 + 10;
                begin[serial].y = ((y - 10) / 25) * 25 + 10;
            }
        } else {
            if (evt.getX() > 300 && evt.getX() < 550 && evt.getY() > 10 && evt.getY() < 260) {
                begin[0].x = ((evt.getX() - 10) / 25) * 25 + 10;
                begin[0].y = ((evt.getY() - 300) / 25) * 25 + 10;
            }
        }
        repaint();
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        Point point = new Point(evt.getX(), evt.getY());
        for (int i = 0; i < 5; i++) {
            if (getNumber(point, i)) {
                serial = i;
                System.err.println(i);
                break;
            }
            serial = -1;
        }
    }//GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(anhnen.getImage(), 0, 0, 560, 270, null);
        for (int i = 0; i < 11; i++) {
            g.drawLine(10, 10 + (i * 25), 260, (i * 25) + 10);
            g.drawLine(10 + (i * 25), 10, 10 + (i * 25), 260);
        }
        for (int i = 0; i < 11; i++) {
            g.drawLine(300, 10 + (i * 25), 550, (i * 25) + 10);
            g.drawLine(300 + (i * 25), 10, 300 + (i * 25), 260);
        }
        g.drawImage(tau1[arrImage[0]].getImage(), begin[0].x + XY1[arrImage[0]].x, begin[0].y + XY1[arrImage[0]].y, tau1[arrImage[0]].getImage().getWidth(this), tau1[arrImage[0]].getImage().getHeight(this), null);
        g.drawImage(tau2[arrImage[1]].getImage(), begin[1].x + XY2[arrImage[1]].x, begin[1].y + XY2[arrImage[1]].y, tau2[arrImage[1]].getImage().getWidth(this), tau2[arrImage[1]].getImage().getHeight(this), null);
        g.drawImage(tau3[arrImage[2]].getImage(), begin[2].x + XY3[arrImage[2]].x, begin[2].y + XY3[arrImage[2]].y, tau3[arrImage[2]].getImage().getWidth(this), tau3[arrImage[2]].getImage().getHeight(this), null);
        g.drawImage(tau4[arrImage[3]].getImage(), begin[3].x + XY4[arrImage[3]].x, begin[3].y + XY4[arrImage[3]].y, tau4[arrImage[3]].getImage().getWidth(this), tau4[arrImage[3]].getImage().getHeight(this), null);
        g.drawImage(tau5[arrImage[4]].getImage(), begin[4].x + XY5[arrImage[4]].x, begin[4].y + XY5[arrImage[4]].y, tau5[arrImage[4]].getImage().getWidth(this), tau5[arrImage[4]].getImage().getHeight(this), null);
    }

    public void setIsClient(boolean is) {
        isClient = is;
    }

    public void setStatus(int s) {
        status = s;
    }
}
